### ISSUE TITLE
Who's the planner?

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#1]
This person should be in charge of making planning decisions, but doesn't need to make final calls on any individual decision. 

The choice of planner should be added to the following document:
https://docs.google.com/spreadsheets/d/1LBgVLnVUHHhqa2I6a8ADLojlVGCh1KfShTPzW-_TY3Q/edit?usp=sharing

**Comment by CarolynT2017** [comment]
@azoff  I think we have a good "work flow" and collaboration going on with planning, yes?
