### ISSUE TITLE
What is the date of the wedding?

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#10]
Depends on #11

**Comment by CarolynT2017** [comment]
Take into consideration weather of the season. Farmers Calendar is a good resource.

**Comment by azoff** [comment]
2018 Kosher-Style Dates

- 31 December 2017, Sunday - New Year’s Eve
- 06 January 2018, Saturday - 05:05PM Sunset
- 13 January 2018, Saturday - 05:12PM Sunset
- 14 January 2018, Sunday - MLK Sunday
- 20 January 2018, Saturday - 05:19PM Sunset
- 27 January 2018, Saturday - 05:27PM Sunset
- 03 February 2018, Saturday - 05:34PM Sunset
- 10 February 2018, Saturday - 05:42PM Sunset
- 17 February 2018, Saturday - 05:50PM Sunset
- 18 February 2018, Sunday - President’s Day Sunday
- 24 February 2018, Saturday - 05:57PM Sunset
- 03 March 2018, Saturday - 06:04PM Sunset
- 10 March 2018, Saturday - 06:11PM Sunset
- 27 May 2018, Sunday - Memorial Day Sunday
- 02 September 2018, Sunday - Labor Day Sunday
- 06 October 2018, Saturday - 06:44PM Sunset
- 07 September 2018, Sunday - Columbus Day Sunday
- 13 October 2018, Saturday - 06:33PM Sunset
- 20 October 2018, Saturday - 06:24 Sunset
- 27 October 2018, Saturday - 06:15PM Sunset

**Comment by CarolynT2017** [comment]
CONFIRMED! 

Suncadia
Sunday May 27, 2018
(Sunday of Memorial Day weekend)
