### ISSUE TITLE
Where is the wedding venue

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#11]
The quintessential question. Use this ticket to discuss/track options.

Things to consider: 
- Venues with an open vendor policy could be significantly cheaper
- Need to lock down venue and date in tandem before anything else can happen. 
- Having flexible dates means more options for venues and less stress
- Check with your friends about their feelings about giving up a 3-day weekend for you wedding.        - Run the date by close family and friends before locking in the date to make sure it works
- wedding + venue at same location = important to Carolyn and Jon

**Comment by CarolynT2017** [comment]
@azoff once we have the timeline, we can decide if going up to Seattle the weekend of 2/24 makes sense to get our toes wet with venues. Also, we should plan a weekend (mini getaway?!) for NorCal venue spots as well. 

But first we need a list of ones that we want to check out. 

PS: I love you

**Comment by CarolynT2017** [comment]
# Venues on the Radar

**PacNW**
- Alderbrook (Hood Canal)
- Kiana Lodge
- The Admiral House

**NorCal**
- Half Moon Bay (Ritz Carlton? - no)
- Mavericks Event Center
- 
- 
- 

**Other**?

**Comment by CarolynT2017** [comment]
@azoff  - the list from Brooke is below:



Alderbrook https://www.alderbrookresort.com/weddings/

Fireseed http://fireseedcatering.com/weddings-events/

Suncadia Inn https://www.destinationhotels.com/suncadia-resort/weddings

Swifwater Cellars https://www.swiftwatercellars.com/weddings/

Trinity Tree Farm http://www.trinitytreefarm.com/weddings/

Grand Ridge Manor http://thegrandridge.com/

Cave B Winery http://www.cavebinn.com/weddings/

Lord Hill Farms http://lordhillfarms.com/

Woodmark Hotel http://www.thewoodmark.com/seattle-wedding-venues.php

Rock Creek Gardens http://rockcreekgardensvenue.com/

Tsillan Cellars http://www.tsillancellars.com/events/weddings/

Dairyland https://www.woodlandmeadowfarms.com/blank

Lodge at Fall City Farms http://www.herbanfeast.com/venues/the-lodge/

Frogsong Gardens http://www.herbanfeast.com/venues/froggsong-gardens/

Sanders Mansion http://www.sandersestate.com/

Inglewood Golf Club http://www.inglewoodgolfclub.com/

Snoq. Ridge Golf Club http://www.clubatsnoqualmieridge.com/special-events/weddings

Thornewood Castle http://www.thornewoodcastle.com/

**Comment by CarolynT2017** [comment]
Consider:
- Venues with an open vendor policy could be significantly cheaper

**Comment by CarolynT2017** [comment]
- wedding + venue at same location = important to Carolyn and Jon

**Comment by CarolynT2017** [comment]
If outside: Have a backup venue and/or tents. 

Outdoor weddings can be more expensive because of all of the extra planning/supplies, etc.

**Comment by CarolynT2017** [comment]
Lock down the venue with a deposit ; get a contract. Once you have a venue you can send out the save-the-date cards.

**Comment by CarolynT2017** [comment]
be skeptical, but don't discount venue advice. They know the venue well and they can offer great suggestions.

**Comment by azoff** [comment]
Try to find a venue that doesn't need a lot of extra stuff to look beautiful

**Comment by azoff** [comment]
### Alderbrook

- Site Fee? 5000 (Summer), 4000 (Spring or Late Summer)
- Open Vendor Policy? Not for staff or catering/beverages
- Beverage Fees? Open Tab, Full Bar
- Lighting? Nope.
- Day exclusive? Yes.
- Best Months? July-Sept.
- Tents Included? No. 3-4K via hotel, increases 40/pp
- Catering? In-house chef, min $80pp food+Bev. Costs negotiated after deposit. Family style avail
- Dessert Avail? Yes, but no fee to bring in
- Kosher Avail? Yes 
- Rehersal Dinner? Food+Bev is only cost or Lady Alderbrook Yacht 40ppl, 500/hr. Mooring available, Handicap accessible
- Heat Lamps? Yes
- Flowers? No, but they offer a staging room
- Room Rates? 269+, Cottages 499+
- Deposit? Non-refundable.
- Contract? Yes.
- Lights Out? 11PM, Lounge till 1AM
- Decoration Included? Couches (they'll help)
- Staff Included? Waiters
- Perks? Free Valet, Pet Friendly, Sea Planes, Sauna
- ADA? Yes
- Dining Outdoors? Yes
- Downsides? Small Reception Room, No Uber or Taxi
- AV/PA? Projectors, Speakers
- Activities? Boating, shellfish, spa, BBQ, picnics, Alderbrook Golf+Yacht, walking trails
- Overflow? Shelton Little Creek
- Transportation? Courtesy Van (seats 6)
- Hair + Makeup? Offered at Spa (in pamphlet)

**Comment by azoff** [comment]
twanoh state park in hood canal

**Comment by azoff** [comment]
Twanoh falls beach club

**Comment by azoff** [comment]
LakeDale Resort on San Juan Island http://www.lakedale.com/wedding-and-receptions/

**Comment by azoff** [comment]
### Suncadia

Contact: Bonney <bcarter@suncadia.com> ext. 6422

- Music? 
- Equipment Rentals? Tables and chairs, offering new banquet chairs soon. China, silverware, glasses. Includes setup and teardown (unless @lookout)
- Site Fee? 2000 regardless, though flexible
- Open Vendor Policy? No food or beverage, yes for dessert.
- Beverage Fees? Corkage fee, 250/keg 20/wine. 3hr 34-42/pp + 15/hr or open tab.
- Lighting? 
- Day exclusive? Not usually
- Best Months? May-June, Sept-Aug
- Tents Included? 
- Catering? Menu, Family Style available. 100/pp wedding, off season 58/pp
- Dessert Avail? Yes, though you can bring your own food in. Or a rabbi van watch
- Kosher Avail?  Bring your own in
- Rehersal Dinner? 
- Heat Lamps? 
- Flowers? 
- Room Rates? 
- Deposit? Percentage of the food an Bev minimum
- Contract? 
- Lights Out? 10PM, then 12AM
- Decoration Included? 
- Staff Included? 
- Perks? Golf, Trails, Mountain Views
- ADA? I think. Probably not @lookout
- Dining Outdoors? Yes
- Downsides? Inn is gone 2018, Lookout is less accessible, remote
- AV/PA? 
- Activities? 
- Overflow? 
- Transportation? Yes. Shuttles. Fees are 7pp
- Hair + Makeup? 
- Capacity? 120

**Comment by azoff** [comment]
### Kiana Lodge

Contact: Pam

-Dates: June 24th, July 3rd 2017, September 3 weekends. August 31st. July 14 2018 on.
- Music? Only inside
- Equipment Rentals? Tables and chairs included (28 long). Plating and drinks, nice linens (6pp). Teardown night of, staged but not picked up
- Site Fee? 1000 to 5000, +2000 for the whole day (12-12 available). +300 bartender, +500 planner, Indian and sales tax, owned by tribe.
- Open Vendor Policy? Nope.
- Beverage Fees? Open tab w/limit. Up to two bartenders. 
- Lighting? No extra
- Day exclusive? Yes
- Best Months? June-Sept
- Tents Included? Won't work. Indoor options
- Catering? 60/pp food and beverage min.
- Dessert Avail? Bring own
- Kosher Avail? Bring food in
- Rehersal Dinner? People tend not to do it here. Friday for a weekend
- Heat Lamps? Yes
- Flowers? Setup at the start
- Room Rates? No rooms - Casino option 15% discount only with rehearsal or brunch
- Deposit? Just site fee. Non refundable.
- Contract? Yes.
- Lights Out? 11 (flexivle)
- Decoration Included? No. Setup required, no nails or staples.
- Staff Included? Bar, waiters and cleanup
- Perks? Groom's room, Actual sandy hook
- ADA? Yes.
- Dining Outdoors? Yes.
- Downsides? No weeping willow, no time outside of hours.
- AV/PA? For toasts, not dancing. Projector
- Activities? Hiking, downtown Poulsbo, golf course, sea sports
- Overflow? Poulsbo guest house and best western
- Transportation? 1 Uber, Taxi. Complementary from the casino.
- Hair + Makeup? No.
- Capacity? 300

**Comment by azoff** [comment]
### Port Gamble
Contact: Eric Ayala
Dates: May 27th, or summer 2018

- Music? Only inside
- Equipment Rentals? Tables and chairs included. Arbor to borrow. Flexible cleanup
- Site Fee?  2500-3600
- Open Vendor Policy? Yes
- Beverage Fees? Bring your own, licensed bartrnder. No big kegs
- Lighting? Bring in own
- Day exclusive? Yes
- Best Months? July-Aug
- Tents Included? Yes
- Catering? Bring your own
- Dessert Avail? Bring own
- Kosher Avail? Bring food in
- Rehersal Dinner? Port Ludlow
- Heat Lamps? Yes
- Flowers? All day
- Room Rates? No rooms - Partner option 20-30% discount only with rehearsal or brunch
- Deposit? 50% due, non-refundable. 400-650 sec deposit
- Contract? Yes.
- Lights Out? 10 (bar available)
- Decoration Included? No. 
- Staff Included? Just tabling
- Perks? Lawn games
- ADA? Yes
- Dining Outdoors? Yes.
- Downsides? Cemetary, Early night, Late night casino might be only option 
- AV/PA? Not outdoors, but yes power. PA wireless included and projector.
- Activities? Olympic Sportsman, Trails, Golf
- Overflow? No
- Transportation? Cabs and Shuttles. Complementary from the casino.
- Hair + Makeup? No.
- Capacity? 180

**Comment by CarolynT2017** [comment]
More Eastern Washington venues:

http://www.ritterfarms.net/site/9060f77d036a4e7ab92acd61b5bcfc0b/default?url=http%3A%2F%2Fritterfarms.net%2FRental_Policies.html


https://www.theknot.com/marketplace/salish-lodge-and-spa-snoqualmie-wa-252986

**Comment by CarolynT2017** [comment]
More:

http://www.clubatsnoqualmieridge.com/special-events/weddings

**Comment by azoff** [comment]
@CarolynT2017 -did you mean to close this ticket?

**Comment by CarolynT2017** [comment]
San Juan islands:

https://www.visitsanjuans.com/members/rosario-resort-spa-weddings-venue

https://www.visitsanjuans.com/members/doe-bay-resort-and-retreat-weddings

**Comment by CarolynT2017** [comment]
Northern California:

http://www.herecomestheguide.com/northern-california/wedding-venues/bodega-bay-secret-gardens


http://www.tiptopplanning.com/blog/2016/5/16/12-redwood-wedding-venues-in-the-bay-area

**Comment by azoff** [comment]
http://themountainterrace.com/

**Comment by azoff** [comment]
Secret Garden

* Size? 150
* Available? Mostly avail in 18, memorial day?
* Music? Most of the time it's not an issue; bass is the issue. Sonoma county sound 30decibles.
* Equipment Rentals? Flatware, table cloths required.
* Site Fee? 4900-5900
* Open Vendor Policy? Yes, but preferences (they do all the setup and tear down)
* Beverage Fees? Open, friends encouraged
* Lighting? yes!
* Day exclusive? 9hrs (flexible)
* Best Months? Fall is more dependable than spring
* Tents Included? Yes
* Catering? No
* Dessert Avail? No
* Kosher Avail? Open
* Rehersal Dinner? Friday is free
* Heat Lamps? Yes
* Flowers? No, but pretty already
* Room Rates? none, venue close by with wine tasting and houses
* Deposit? 50% with most back
* Contract? Basic guarantee for weather
* Lights Out? 10PM sound, 11PM, 
* Decoration Included? Tables and chairs and flowers
* Staff Included? No
* Perks? Grooms Room, Birdhouse, Bride's room, BBQ, Cypres Buffet Table
* ADA? I think, need help
* Dining Outdoors? Yes, with free tent
* Downsides? 10PM sound ordinance
* AV/PA? PA
* Activities? Golf, Fishing Boats, Horseback Riding, Kayaking, Bodega Head (2mi)
* Overflow? Lots of rental houses, 50 car lot
* Transportation? Local shuttle with rentable houses and late night options
* Hair + Makeup?

**Comment by CarolynT2017** [comment]
@azoff  - let's use our wedding planning time tomorrow to call the Secret Gardens' references. We should do so as early as possible (i.e. as close to 5:30pm as possible) so we do not intrude on evenings).


- Mandy and Ethan: 925. 890.. 5362
- Chelsea and Arajez. They had a mixture of East Indian and American Wedding ..simply fabulous!!! it was so much fun.  You may  call or text .. 303. 921. 3587. 
- Jacqueline and Scott. The mother is Mary and you may be speaking with Mary . Phone: 925 - 586 - 8063.






Post here what questions to ask. A few of mine:

- was the noise parameters an issue?
- Did people have enough options RE: housing/lodging?
- Where did they do their rehearsal dinner?
- What did they do for an after party?
- Mosquitos, etc.?
- Setup for ceremony/flow.
- any surprises? 
- Favorite thing? Most negative thing?

**Comment by azoff** [comment]
Yes!

**Comment by CarolynT2017** [comment]
@azoff - scratch that. Secret Gardens is sadly "out" for 2018, due to our limited flexibility with dates. I will let Hannah know we will not be calling the references.

**Comment by CarolynT2017** [comment]
@azoff  - other locations to consider for when my parents are in town. Let me know which ones you like and I will reach out:

https://www.herecomestheguide.com/northern-california/wedding-venues/piedmont-community-hall

http://www.rockefellerlodge.com/index.html

http://www.deerparkvilla.com/

**Comment by CarolynT2017** [comment]
@azoff  - please look at the list tomorrow night when I am up in Seattle. I want to may appts, especially since my parents will be joining us.

We also need to let Hannah when we will be at Secret Gardens.

+ we need to book a place for this weekend.

**Comment by azoff** [comment]
@CarolynT2017  The Piedmont community center is actually great, but it doesn't have any water. It's also kind  not really a destination 

 The Rockefeller Center seems a little Godey, and probably won't be open very late for us. It looks nice though, just not sure if it's the right vibe. 


Deer park looks great too, and i have an email from them i'll forward you :)

**Comment by CarolynT2017** [comment]
@azoff found one more:

http://www.herecomestheguide.com/northern-california/wedding-venues/amphitheatre-of-the-redwoods-at-pema-osel-ling-retreat-center

**Comment by azoff** [comment]
Outdoor Art Club

Contact: Mary Ware
Dates: 2018 3day weekends avail

- Music? Grand piano 150 to rent, free upright piano to use. Need to check for outside music.
- Equipment Rentals? Tables and chairs included. Suggest caterers to do cleanup and linens.
- Site Fee? 3900
- Open Vendor Policy? Yes, restricted.
- Beverage Fees? Bring your own, suggest caterer to do bartender
- Lighting? Bring in own
- Day exclusive? Yes
- Best Months? Late April-May
- Tents Included? No
- Catering? Strong preferred, commercial kitchen
- Dessert Avail? Bring own
- Kosher Avail? Bring food in
- Rehersal Dinner? Mill Valley Inn, piazza d'angelo
- Heat Lamps? No
- Flowers? Already very beautiful
- Room Rates? No rooms
- Deposit? 1500 refundable, 1950 total + insurance.
- Contract? Yes.
- Lights Out? 9:30 doors shut. Guests/Music out by 11.
- Decoration Included? No, but it's beautiful outside. Available all day for setup.
- Staff Included? No
- Perks? Close to SF, Nice photo ops
- ADA? Yes
- Dining Outdoors? Possible. Need to ask.
- Downsides? Small dinner/reception area.
- AV/PA? Fee associated with AV system setup
- Activities? 
- Overflow? Many walking distance hotels
- Transportation? Ubers, Wings, 
- Hair + Makeup? No.
- Capacity? 150

**Comment by azoff** [comment]
Deer Hill Villa

Contact: Mark Dates: February Avail (not likely), sunset weddings possible

* Music? Low key outside
* Equipment Rentals? Outside banquet tables. Bar glasses provided. Tabletop up is the caterer. Rent: Farm tables, queen tables, maybe mix and match. Maybe consider chandeliers. Takedown occurs night of but pickup day after.
* Site Fee? Buyout. 6K-9K + tax, 10% off w/SPD special
* Open Vendor Policy? Partial
* Beverage Fees? Required packages, liquor they have to be involved. 30-50/pp
* Lighting? Yes!
* Day exclusive? Yes. Rehearsals up until noon. Can come in until 10.
* Best Months? April-September 
* Catering? Highly preferred. Wait staff. Setup teardown
* Dessert Avail? No.
* Kosher Avail? Yes.
* Rehersal Dinner? On a Thursday, dinner in fairfax
* Heat Lamps? Provided
* Flowers? Probably not needed, maybe for tables
* Room Rates? No, but maybe Fairfax inn
* Deposit? Moving no charge, not refundable
* Contract? Yes
* Tents? Included at cost
* Lights Out? Midnight or 130AM
* Decoration Included? 
* Staff Included? Maintenance, parking, security, food and beverage, bartenders 
* Perks? 101 years of weddings, Ghirardelli family, massive parking lot, Bocce Ball court, prohibition era bar groom's room + early arrivals, Zen Grove, Corn Hole
* ADA? Yes
* Dining Outdoors? Yup, transition during cocktail hour
* Downsides? A little impersonal
* AV/PA? Built in, very nice
* Activities? Biking, Hiking, Fly fishing
* Transportation? Park overnight is fine (back by 10)
* Hair + Makeup? Nope
* Capacity? 300
* Parking? Passes available

**Comment by azoff** [comment]
Piedmont Community Hall

Contact: John ?? Dates: Need to follow

* Music? Piano in another building, talk to John or rent it. Storage can be arranged, very flexible
* Equipment Rentals? They have chairs and tables. 
* Site Fee? 3500 + 200ph
* Open Vendor Policy? Yes, with preferred list
* Beverage Fees? Open. Has to be served by a licensed bartender. No hard alcohol drinks.
* Lighting? Need to rent
* Day exclusive? Yes
* Best Months? April-September
* Tents Included? No, but they have canopies 
* Catering? Full kitchen
* Dessert Avail? Do your own
* Kosher Avail? Do your own
* Rehersal Dinner? On your own
* Heat Lamps? No, preferred vendors. Make sure they work!
* Flowers? Probably not needed, maybe for tables
* Room Rates? Nope
* Deposit? All but 50, half after 6mo.
* Contract? Yes
* Lights Out? Music off by 11PM
* Decoration Included? No
* Staff Included? 2 people on staff
* Perks? Potentially tax-deductible, tea house for dressing, main hall is huge for dancing 
* ADA? Yes, barely 
* Dining Outdoors? Yes.
* Downsides? Overflow is lacking
* AV/PA? Old PA system, but it works. Help included.
* Activities? Higher end community
* Overflow? Oakland
* Transportation? Uber / Lyft
* Hair + Makeup? No
* Capacity? 200
* Parking? Passes available

**Comment by azoff** [comment]
Pema Osa Ling

Contact:  Dates: 

* Music? 
* Equipment Rentals? 100 Chairs + overseeing setup.
* Site Fee? 9200
* Open Vendor Policy? 
* Beverage Fees? BYOB + Licensed personnel on staff 
* Lighting? additional rental
* Day exclusive? Friday 3PM - Sunday 12PM
* Best Months? May-Oct
* Tents Included? 
* Catering? Rehearsal (35req), Dinner (100) and Brunch Required (35req)
* Dessert Avail? own responsibility
* Kosher Avail? No. orHalva catering
* Rehersal Dinner? 35min on site
* Heat Lamps? Yes
* Flowers? centerpieces
* Room Rates? 1800 / 40 / night
* Deposit? 
* Contract? Responsible for 40 bed nights (1800)
* Lights Out? 10PM indoors, 2AM lights off
* Decoration Included? No, 1PM setup friday allowed.
* Staff Included? 
* Perks? Buddist monastery, compound, room for lawn games
* ADA? Sorta
* Dining Outdoors? yes
* Downsides? way out there
* AV/PA? 
* Activities? Pool, hiking
* Overflow? 
* Transportation? we'll need shuttle
* Hair + Makeup? 
* Capacity? 300
* Parking?

**Comment by CarolynT2017** [comment]
@azoff 

Sleeping Lady: http://www.sleepinglady.com/weddings.php

Crystal Mountain Lodge: https://crystalmountainresort.com/summer/summer-weddings/

Mountain Springs: http://www.mtsprings.com/wedding-leavenworth-wa

Rio Vista: http://www.riovistaweddings.com/

**Comment by CarolynT2017** [comment]
@azoff  - please let me know any favs!
