### ISSUE TITLE
Who is our wedding planner? (If applicable.)

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#12]
Depends on #9. We can discuss options and make a call here.

**Comment by CarolynT2017** [comment]
Jon and Carolyn have meeting with Raeanne and Brooke on 2/6/2017 at noon. @azoff please make sure it is on your calendar! Via Google Hangouts.

**Comment by CarolynT2017** [comment]
Consider consulting call with a planner to determine how involved a planner we might need

**Comment by azoff** [comment]
@CarolynT2017 let's get their rates on the budget

**Comment by CarolynT2017** [comment]
Raeanne and Brooke Balzarini
