### ISSUE TITLE
Lock down Guest List

### ISSUE THREAD

**Issue by CarolynT2017** [azoff/wedding#16]
Finalize guest list. 

https://docs.google.com/spreadsheets/d/1SzbNfzFUwWuxsQe6YnHsxt7jaB71v_9qGuHDETcjoVg/edit?usp=sharing

1) Thayer family additions - DONE
2) Azoff family additions - OUTSTANDING
3.) Remove yellow/'maybes' as-wanted ("B-list?)

**Comment by CarolynT2017** [comment]
@azoff  - please follow-up with your parents to get the additional family members that we need to add.

**Comment by CarolynT2017** [comment]
Consider inviting parents friends/family, because they are the ones who will give you the most $$

**Comment by CarolynT2017** [comment]
@azoff  - structure the guest list in a way that allows people to move around easily.

**Comment by azoff** [comment]
I just messaged my parent, gonna try to push on getting their list as well

**Comment by azoff** [comment]
My dad just got back to us with an email, I'll add the names to the list

**Comment by CarolynT2017** [comment]
@azoff 

Can you please add your mom's list to the spreadsheet?

Corrections: 
Perlette - 4 kids  3 are married.
Nissim+ Debra ( 7 kids , 4 are married). 
Eva and shlomo have 12 kids and 6 are married
Osnat and Shmuel Har 10 kids and 2 are married
Yossi is not married . 

Daniel- has 3 kids 
Michel and Sinta are divorced (they have 2 kids: Mathew and laura.)
Sandra and ?   (Have 2 kids Nataniel &??)
Corine is not married

Rosette and Amram who passed away ( have 2 kids:
Tamar + Xavier  have 3 kids ( the 2 boys are getting married this summer one after the other... ) 
Samuel is not married

Betsalel + Hanah have 4 kids.
Or-el + Ira ( 2 daughters )
Adva + Shlomo ( 1 son) 
Eliyah + Omer
Liat + Yariv (2 Daughters 1 son)

Helene & David have 2 kids:
Netanel + Avital
Inbar + Yariv ( 4 kids)

Esther + Henry have 4 kids:
Joane + Daniel ( 3 kids )
Yahel + Patrick  ( 1 son)
Judith + ?  ( 2 sons)
Orelia + Marc

Gad + Nicole have 3 sons:
Yaniv+? ( 1 daughter)
Erez
David

Holly and Ronit are divorced . They have 3 kids:
Keren ( a son & a daughter)
Shi 
Shirley ( 2 daughters)

Albert-

Itsik and Barbara are divorced . They have 3 kids( Avishai, Yarden and Matan)

Yaakov + Tali have 4 kids( eden, Youval, Ron, Or)

Maurice + Magi have 3 kids: Gaby, yael, Noa

Marki

**Comment by CarolynT2017** [comment]
@azoff done!
