### ISSUE TITLE
Define the support role(s)

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#2]
These individuals should be considered as part of the supporting cast for the planner (see #1). There can be more than one support role, though at least one should be called out for the purposes of this ticket. 

The responsibilities and names of the people in the support roles should be added to the following document: 
https://docs.google.com/spreadsheets/d/1LBgVLnVUHHhqa2I6a8ADLojlVGCh1KfShTPzW-_TY3Q/edit?usp=sharing

You can close this ticket once it's started, and then continue to add to it as the list grows.

You can close this ticket once it's started, and then continue to add to it as the list grows.

**Comment by CarolynT2017** [comment]
Opportunities:
- rehearsal dinner
- Henna
-

**Comment by CarolynT2017** [comment]
@azoff I think we have a good "work flow" and collaboration going on with planning, yes?
