### ISSUE TITLE
Define things you care to be involved in.

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#3]
We can use this document to track it:
https://docs.google.com/spreadsheets/d/1dK9Qc0sDrupmggAhEI0WGmGt4Aqwa1ySMBYNCvUgFI0/edit?usp=sharing

You can close this ticket once it's started, and then continue to add to it as the list grows.

**Comment by CarolynT2017** [comment]
@azoff I think we have a good "work flow" and collaboration going on with planning, yes?
