### ISSUE TITLE
Buy Boutonnieres

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#40]
Order one or two extra, just in case.

**Comment by CarolynT2017** [comment]
https://www.pinterest.com/pin/AbY6O2efRBYTUYLDacNcwHo-0jtmq4irW448uYrvWAlHh4DwXipIJwM/

**Comment by CarolynT2017** [comment]
@azoff FYI that I ordered these with the florist. + one for ring bearer (Carter) and one for our dads. 

It will look something like this: https://www.pinterest.com/pin/AdoHTZzpfiSwGOaAfcYD8iNMeKnmNIx4GyGb2bB4dUJVIMC5zIBzVO0/
