### ISSUE TITLE
Buy A Wedding Dress

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#41]
The flower aesthetic flows from the wedding dress

**Comment by azoff** [comment]
there are freedoms in constraints: putting a budget on wedding dresses helps filter out a lot of the noise

**Comment by azoff** [comment]
Mark down the relevant dates for alterations and refunds on the timeline https://docs.google.com/spreadsheets/d/1iBnCb30ZhpUfUmUnQTwNIE5o4dRpimplTAO-s81MQl8/edit#gid=0

**Comment by azoff** [comment]
Avoid bridal salons due to all the up selling

**Comment by azoff** [comment]
Potentially, get a wedding dress designed in Vietnam

**Comment by CarolynT2017** [comment]
DONE!
