### ISSUE TITLE
Who's our videographer?

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#46]
Maybe hit up Richard?

**Comment by CarolynT2017** [comment]
I like this video : https://ql.mediasilo.com/#ql/57727d8ae4b06a16dc83c93b/8f5d447f-550c-43dc-aef6-453d3caa1517

**Comment by CarolynT2017** [comment]
https://www.facebook.com/andreabrassington/posts/10208236293216768

**Comment by CarolynT2017** [comment]
possibility: Saskia's husband: http://www.joshuapotter.com

They have a January- May promotion on dual services. Waiting to hear back what this is!

**Comment by CarolynT2017** [comment]
Confirmed with Saskia (photographer) and her husband Joshua (videographer)
