### ISSUE TITLE
Who's our photographer?

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#47]
When you consult with a photographer, check to see if they offer video as well. Book your photographer before #46 

Ask about RFP: rights of usage and full resolution files before you book

**Comment by azoff** [comment]
wedding photos span beyond you: there are lots of other people who want photos too.

**Comment by azoff** [comment]
Offer your friends a few dollars to take pictures, to augment A professional photographer. This can also be done using a hashtag.

**Comment by azoff** [comment]
Try out Instagram to see if there any wedding photographers you might like

**Comment by azoff** [comment]
make sure to have a timeline ready for the photographer, so that you don't have to answer a bunch of questions #13

**Comment by azoff** [comment]
Compare the photographers rate to create an album, with the rates of online services such as Shutterfly.

**Comment by azoff** [comment]
For the wedding portraits, try to find a photographer that doesn't charge by the shoot but rather by the hour. Or, better yet, just try to see if they can include it with the price of their reservation.

**Comment by azoff** [comment]
For the wedding portraits #50, try to find a photographer that doesn't charge by the shoot but rather by the hour. Or, better yet, just try to see if they can include it with the price of their reservation.

**Comment by azoff** [comment]
Photographers will sometimes offer a photo booth #51 as an add-on. Though, if you go this route, you may need to bring decorations. You may also need to hire a second photographer.

**Comment by azoff** [comment]
One way to test the photographer is to have them do engagement photos for you #54

**Comment by CarolynT2017** [comment]
I have reached out to Saskia Potter (connection via ADURO). Her response:

Hi Carolyn,

Belated congratulations! How exciting. :) What venue are you guys looking at? 

As of now both Joshua and I are available for your date and would love to chat more about what you're looking for in regards to coverage. 

I'll attach my pricing information here, let me know if I can help with any questions at all. Joshua's pricing starts at $2200 I believe but I'll have him forward me his rates so I have more exact pricing for you. We normally run a promotion for the for January-May weddings where we do a combined package but we haven't established what that will be for 2018 yet as we are just wrapping this year up. I should have that information in the next few weeks and can pass that on.

Are you interested in engagement portraits?

I am in Italy at the moment but will be back on the 8th. Would you be interested in grabbing a cup of coffee and chatting further? If so, I'd love to get something on the books. It's easier to talk logistics in person and get a feel for how photography on the big day works/how much time is needed etc. Let me know if you're up for a coffee meet up! 

Warmly,
Saskia 
!

[Uploading pricing1.jpg…]()



https://www.facebook.com/saskiapotterphotography/photos/a.987348844648529.1073741828.140040132712742/987350791315001/?type=3&theater

**Comment by azoff** [comment]
Saskia prefers a first look before the ceremony to save time and get a debrief before the wedding

**Comment by azoff** [comment]
First look with portraits

**Comment by azoff** [comment]
She has a questionnaire that sets us up for which families and photos we want

**Comment by azoff** [comment]
Extended family photos would occur during cocktail hour

**Comment by azoff** [comment]
We might get stolen around sunset for a golden hour shot
