### ISSUE TITLE
Establish ground rules

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#5]
The ground rules are just a formal document outlining a personal mantra for dealing with each other during this process. For instance, we can try to start here:

https://github.com/azoff/wedding/wiki/Ground-Rules

Just make sure we're all aligned before closing this ticket. It can always be expanded on later.

**Comment by CarolynT2017** [comment]
@azoff  - would you say we are aligned?

**Comment by azoff** [comment]
@CarolynT2017 barely

**Comment by azoff** [comment]
:P
