### ISSUE TITLE
Create the wedding website

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#53]
Make sure it has the wedding hashtag on it!

**Comment by azoff** [comment]
- Make sure to have an FAQ section on the website
- Include the dress code in the FAQ.
- @CarolynT2017 really wants bios for each of the people in the wedding party

**Comment by azoff** [comment]
Consider squarespace or a value-add to planning software #57 so you don't waste your precious time making websites

**Comment by azoff** [comment]
Add a form for handling RSVPS #23

**Comment by azoff** [comment]
Link the registries #62 to the site

**Comment by CarolynT2017** [comment]
@azoff  - information that needs to be on the website (in separate tabs/drop down "fanning" tabs):

1.) Registry

2.) Weekend Events

3.) You think you can dance?
Free-form for songs they want to hear?

4.) Accommodations

5.) Wedding Party

6.) A note from C&J

7.) Things to do

8.) FAQ
      - attire
      - weather
      -

**Comment by azoff** [comment]
I was hoping to buy two types of domains, one type will be used for short links (which we can use in our Save the Dates, etc.), the other will be used for the website itself. Here are some available options:

Short Links:
- jact.wed
- zoff.ly

Long Links:
- carozoffthe.market
- carozoffthemarket.com
- zofflyn.com
- ohhaimay.wedding
- haimay.wedding

**Comment by CarolynT2017** [comment]
@azoff

I don't love any of the short links. Could we do: 

JA_CT.wed

??

For long link, I like: carozoffthemarket.com

What are your favs?

**Comment by azoff** [comment]
Why don’t you help me out:

Go on domai.nr and try to find short links. The long link is fine by me, though I kinda like carozohffthe.market a little better

**Comment by CarolynT2017** [comment]
Im OK with that one too.

The only thing I worry about is the older generation not knowing that a URL doesn't need to end in .com (they may add it anyways, which will lead to confusion). 

Carolyn Thayer, MA
(206)920-9912

**Comment by CarolynT2017** [comment]
Maybe I'm not understanding- why do we need a short link?

Carolyn Thayer, MA
(206)920-9912

**Comment by azoff** [comment]
Well, I mean we can buy both haha

**Comment by azoff** [comment]
Short link is for the save-the-date insert, since there isn’t a lot of room. Also just useful to have to shorten links we give to people for the wedding in general.

**Comment by CarolynT2017** [comment]
@azoff you're amazing!!!
