### ISSUE TITLE
What's your look and feel?

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#6]
This view of the wedding will help clarify many of the questions related to the wedding.

Last we left off, it was "Fireflies, Wood and Water" - if that's still good we can close this ticket :)

Inspiration: https://www.pinterest.com/cthayer2651/wedding/

**Comment by CarolynT2017** [comment]
from @azoff : " I want to be able to smell nature when I get married"

from me: " I want to be on the water - it's grounding and peaceful."

**Comment by CarolynT2017** [comment]
"Fireflies, Wood and Water" !
