### ISSUE TITLE
Create a wedding registry

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#62]
No need to use a registry combining service, it's easier to just use multiple registries.

**Comment by CarolynT2017** [comment]
http://www.heathceramics.com/registry

http://m.gumps.com/registry

https://m.crateandbarrel.com/gift-registry/

https://www.target.com/gift-registry/wedding-registry

Amazon

**Comment by CarolynT2017** [comment]
https://www.zola.com/shop/honeymoon-cash-funds (honeymoon)

https://www.target.com/gift-registry/wedding-registry (Appliances, etc.)

Amazon: everything to fill in gaps (outdoors stuff, etc.)

Gumps: nicer dinnerware, etc.
http://m.gumps.com/registry

Health: everyday dinnerware
http://www.heathceramics.com/registry

Thoughts?

**Comment by azoff** [comment]
The worst thing that could happen is that we put too many registries up and get a hodgepodge of things. Forget about the honeymoon stuff (since clearly I’m in the minority there), and focus on one or two registries if possible. Or, find a service that allows us to combine everything we want into one list.

**Comment by azoff** [comment]
@CarolynT2017 use this form to set up an inbound mailing address for registry items: https://blog.beomni.com/order-stuff-online-ship-directly-to-omni-get-it-delivered-when-you-want-it-302779fbb2bc

**Comment by CarolynT2017** [comment]
done! www.may27.wed/registry
