### ISSUE TITLE
Who is going to manage the budget?

### ISSUE THREAD

**Issue by azoff** [azoff/wedding#7]
The budget, which can be [found here](https://docs.google.com/spreadsheets/d/1iBnCb30ZhpUfUmUnQTwNIE5o4dRpimplTAO-s81MQl8/edit), will house the master list of vendors, expenses, and funds. Decide who will be responsible for updating the budget to include incoming expenses and funds.

Make sure to feel comfortable with the budget sheet before closing this ticket.

**Comment by CarolynT2017** [comment]
@azoff  - I nominate you. :)

**Comment by azoff** [comment]
Me https://www.theknot.com/content/wedding-vendor-tipping-cheat-sheet

**Comment by CarolynT2017** [comment]
@azoff  - I added tip % to the budget doc.

**Comment by CarolynT2017** [comment]
@azoff  - we have a living and breathing spreadsheet.
