### ISSUE TITLE
Anne-Reed's name is spelt wrong

### ISSUE THREAD

**Issue by parnaudo** [azoff/wedding#89]
Couldn't find it in the code so I presume you're pulling it from a database somewhere. This is also the cutest place I've ever seen a couple track wedding tasks @azoff @CarolynT2017 .

**Comment by CarolynT2017** [comment]
Well crap. That's no bueno. The joys of humongous mashed up websites (promise- we know how to spell Anne-Reed's name outside of "AR"). 

Fixing now. Thanks for the catch - and love how it was submitted via GitHub. 😂

Carolyn Thayer, MA
(206)920-9912

**Comment by azoff** [comment]
Thanks for the catch @parnaudo - deploying a fix now!
